In [2]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('practice.db')

def run_query(sql):
    return pd.read_sql_query(sql, conn)

In [3]:
run_query("SELECT name, department, salary FROM employees WHERE department = 'Engineering'")

     name   department  salary
0    Ravi  Engineering   65000
1   Priya  Engineering   72000
2  Suresh  Engineering   58000

In [4]:
run_query("SELECT name, salary FROM employees WHERE salary > 50000")

     name  salary
0    Ravi   65000
1   Priya   72000
2  Suresh   58000

In [5]:
run_query("SELECT name, department, hire_year FROM employees WHERE department = 'Sales' AND hire_year > 2020")

    name department  hire_year
0  Karan      Sales       2022
1  Arjun      Sales       2021

In [6]:
run_query("SELECT name, department FROM employees WHERE department = 'Sales' OR department = 'Marketing'")

     name department
0  Anitha      Sales
1   Karan      Sales
2   Divya  Marketing
3   Meena  Marketing
4   Arjun      Sales

In [7]:
run_query("SELECT name, department FROM employees WHERE department IN ('Sales', 'Marketing')")

     name department
0  Anitha      Sales
1   Karan      Sales
2   Divya  Marketing
3   Meena  Marketing
4   Arjun      Sales

In [8]:
run_query("SELECT name, department, salary FROM employees ORDER BY department, salary DESC")

     name   department  salary
0   Priya  Engineering   72000
1    Ravi  Engineering   65000
2  Suresh  Engineering   58000
3   Divya    Marketing   50000
4   Meena    Marketing   47000
5  Anitha        Sales   45000
6   Arjun        Sales   41000
7   Karan        Sales   38000

In [9]:
run_query("SELECT name, department, salary FROM employees WHERE department = 'Engineering' ORDER BY salary DESC")

     name   department  salary
0   Priya  Engineering   72000
1    Ravi  Engineering   65000
2  Suresh  Engineering   58000

In [11]:
run_query("SELECT department, COUNT(*) AS num_employees FROM employees GROUP BY department")

    department  num_employees
0  Engineering              3
1    Marketing              2
2        Sales              3

In [12]:
run_query("SELECT department, AVG(salary) AS avg_salary FROM employees GROUP BY department")

    department    avg_salary
0  Engineering  65000.000000
1    Marketing  48500.000000
2        Sales  41333.333333

In [13]:
run_query("SELECT department,   COUNT(*) AS num_employees, SUM(salary) AS total_salary,AVG(salary) AS avg_salary,MAX(salary) AS highest_salary,MIN(salary) AS lowest_salary FROM employees GROUP BY department")

,department,num_employees,total_salary,avg_salary,highest_salary,lowest_salary
0,Engineering,3,195000,65000.000000,72000,58000
1,Marketing,2,97000,48500.000000,50000,47000
2,Sales,3,124000,41333.333333,45000,38000

In [14]:
run_query("SELECT department, AVG(salary) AS avg_salary FROM employees GROUP BY department HAVING AVG(salary) > 50000")

    department  avg_salary
0  Engineering     65000.0

In [15]:
run_query("SELECT orders.order_id, employees.name, orders.product, orders.amount FROM orders INNER JOIN employees ON orders.emp_id = employees.emp_id")

   order_id    name       product  amount
0       101  Anitha      Widget A    1200
1       102  Anitha      Widget B     800
2       103   Karan      Widget A    1500
3       104   Arjun      Widget C     600
4       105    Ravi  Service Plan    5000
5       106   Priya  Service Plan    5000
6       107   Karan      Widget B     900
7       108  Anitha      Widget C     700

In [16]:
run_query("SELECT e.name, o.order_id, o.product, o.amount FROM employees e LEFT JOIN orders o ON e.emp_id = o.emp_id")

      name  order_id       product  amount
0   Anitha     101.0      Widget A  1200.0
1   Anitha     102.0      Widget B   800.0
2   Anitha     108.0      Widget C   700.0
3     Ravi     105.0  Service Plan  5000.0
4    Priya     106.0  Service Plan  5000.0
5    Karan     103.0      Widget A  1500.0
6    Karan     107.0      Widget B   900.0
7    Divya       NaN           NaN     NaN
8   Suresh       NaN           NaN     NaN
9    Meena       NaN           NaN     NaN
10   Arjun     104.0      Widget C   600.0

In [17]:
run_query("SELECT e.name, SUM(o.amount) AS total_orders FROM employees e LEFT JOIN orders o ON e.emp_id = o.emp_id GROUP BY e.name ORDER BY total_orders DESC")

     name  total_orders
0    Ravi        5000.0
1   Priya        5000.0
2  Anitha        2700.0
3   Karan        2400.0
4   Arjun         600.0
5  Suresh           NaN
6   Meena           NaN
7   Divya           NaN

In [18]:
run_query("select * from employees")

   emp_id    name   department  salary  hire_year
0       1  Anitha        Sales   45000       2019
1       2    Ravi  Engineering   65000       2021
2       3   Priya  Engineering   72000       2018
3       4   Karan        Sales   38000       2022
4       5   Divya    Marketing   50000       2020
5       6  Suresh  Engineering   58000       2023
6       7   Meena    Marketing   47000       2017
7       8   Arjun        Sales   41000       2021

In [20]:
run_query("select * from orders")

   order_id  emp_id       product  amount  order_date
0       101       1      Widget A    1200  2024-01-15
1       102       1      Widget B     800  2024-02-10
2       103       4      Widget A    1500  2024-01-20
3       104       8      Widget C     600  2024-03-05
4       105       2  Service Plan    5000  2024-02-14
5       106       3  Service Plan    5000  2024-04-01
6       107       4      Widget B     900  2024-03-22
7       108       1      Widget C     700  2024-04-18

In [21]:
run_query("select name, salary from employees where salary > 40000 ORDER BY salary DESC ")

     name  salary
0   Priya   72000
1    Ravi   65000
2  Suresh   58000
3   Divya   50000
4   Meena   47000
5  Anitha   45000
6   Arjun   41000

In [24]:
run_query("select product, COUNT(*) AS total_products ,SUM(amount) As total_amount from orders GROUP BY product")

        product  total_products  total_amount
0  Service Plan               2         10000
1      Widget A               2          2700
2      Widget B               2          1700
3      Widget C               2          1300

In [25]:
run_query("Select e.name, COUNT(o.order_id) AS total_orders FROM employees e LEFT JOIN orders o ON e.emp_id = o.emp_id GROUP BY e.name")

     name  total_orders
0  Anitha             3
1   Arjun             1
2   Divya             0
3   Karan             2
4   Meena             0
5   Priya             1
6    Ravi             1
7  Suresh             0